name: 自动定时触发器

on:
  schedule:
    - cron: '0 */2 * * *'  # 每 2 小时触发一次
  workflow_dispatch:       # 保留手动触发按钮

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # 赋予触发 Workflow 的权限
    steps:
      - name: 触发主编译工作流
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run fastbuild_6.12.23_gki.yml --repo ${{ github.repository }} --ref main
